### **Polynomial Regression**

#### **Implementation from Scratch**

In [ ]:
import numpy as np


class PolynomialRegression:
    def __init__(self, degree=2):
        self.degree = degree
        self.coefficients = None

    def _create_polynomial_features(self, X):
        """
        Convert X into polynomial feature matrix
        """
        X = np.array(X).reshape(-1, 1)

        features = np.ones((len(X), 1))

        for d in range(1, self.degree + 1):
            features = np.hstack((features, X ** d))

        return features

    def fit(self, X, y):
        """
        Train Polynomial Regression using Normal Equation
        """
        X_poly = self._create_polynomial_features(X)

        self.coefficients = np.linalg.inv(
            X_poly.T @ X_poly
        ) @ X_poly.T @ y

    def predict(self, X):
        """
        Predict values
        """
        X_poly = self._create_polynomial_features(X)
        return X_poly @ self.coefficients

    def score(self, X, y):
        """
        Calculate R² Score
        """
        predictions = self.predict(X)

        ss_total = np.sum((y - np.mean(y)) ** 2)
        ss_residual = np.sum((y - predictions) ** 2)

        return 1 - (ss_residual / ss_total)



# Example Usage
import numpy as np

# Sample Data
X = np.array([1, 2, 3, 4, 5, 6])
y = np.array([2, 5, 10, 17, 26, 37])

# Train
model = PolynomialRegression(degree=2)
model.fit(X, y)

# Predict
predictions = model.predict(X)

print("Coefficients:")
print(model.coefficients)

print("\nPredictions:")
print(predictions)

print("\nR² Score:")
print(model.score(X, y))

Coefficients:
[ 1.00000000e+00 -5.68434189e-14  1.00000000e+00]

Predictions:
[ 2.  5. 10. 17. 26. 37.]

R² Score:
1.0


#### **Implementation Using Gradient Descent**

In [6]:
import numpy as np


class PolynomialRegressionGD:
    def __init__(self, degree=2, learning_rate=0.001, epochs=5000):
        self.degree = degree
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None

    def _poly_features(self, X):
        X = np.array(X).reshape(-1, 1)

        features = np.ones((len(X), 1))

        for d in range(1, self.degree + 1):
            features = np.hstack((features, X ** d))

        return features

    def fit(self, X, y):
        X_poly = self._poly_features(X)

        samples, features = X_poly.shape

        self.weights = np.zeros(features)

        for _ in range(self.epochs):

            predictions = X_poly @ self.weights

            error = predictions - y

            gradient = (1 / samples) * (X_poly.T @ error)

            self.weights -= self.learning_rate * gradient

    def predict(self, X):
        X_poly = self._poly_features(X)
        return X_poly @ self.weights


# Test
# Sample Data
X = np.array([1, 2, 3, 4, 5, 6])
y = np.array([2, 5, 10, 17, 26, 37])

# Train
model = PolynomialRegressionGD(degree=2)
model.fit(X, y)

# Predict
predictions = model.predict(X)

# print("Coefficients:")
# print(model.coefficients)

print("\nPredictions:")
print(predictions)

# print("\nR² Score:")
# print(model.score(X, y))


Predictions:
[ 1.7142293   4.95986235 10.0997153  17.13378815 26.06208091 36.88459357]


#### **Using Scikit-Learn**

In [7]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np

X = np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 1)
y = np.array([2, 5, 10, 17, 26, 37])

model = Pipeline([
    ("poly", PolynomialFeatures(degree=2)),
    ("linear", LinearRegression())
])

model.fit(X, y)

predictions = model.predict(X)

print(predictions)

[ 2.  5. 10. 17. 26. 37.]
